# Generated by Django 5.2.5 on 2025-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_booking_options_booking_cancellation_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='travel_book_user_id_69d77e_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='travel_book_booking_4b41a1_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_percentage',
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10),
        ),
    ]
