# Generated by Django 5.2.5 on 2025-10-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
    ]
